# Generated by Django 2.2.5 on 2020-11-24 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Routine',
        ),
    ]
