# Generated by Django 2.2.5 on 2020-11-25 05:33

from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_routine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routine',
            name='points',
        ),
        migrations.CreateModel(
            name='RobotProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('points', djongo.models.fields.JSONField(default={})),
                ('routine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.Routine')),
            ],
        ),
    ]
