# Generated by Django 2.2.5 on 2020-11-26 13:43

from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_auto_20201125_0533'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='robotprofile',
            name='points',
        ),
        migrations.RemoveField(
            model_name='robotprofile',
            name='routine',
        ),
        migrations.CreateModel(
            name='Points',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', djongo.models.fields.JSONField()),
                ('robotProfile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.RobotProfile')),
            ],
        ),
    ]
