# Generated by Django 2.2.5 on 2020-12-01 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0005_auto_20201126_1343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='points',
            name='robotProfile',
        ),
        migrations.DeleteModel(
            name='Routine',
        ),
        migrations.DeleteModel(
            name='Points',
        ),
        migrations.DeleteModel(
            name='RobotProfile',
        ),
    ]
