# Generated by Django 2.2.5 on 2020-12-01 12:29

from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('server', '0006_auto_20201201_1154'),
    ]

    operations = [
        migrations.CreateModel(
            name='RobotProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Points',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', djongo.models.fields.JSONField()),
                ('robotProfile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.RobotProfile')),
            ],
        ),
    ]
