# Generated by Django 2.2.5 on 2020-12-04 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0007_points_robotprofile_routine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='points',
            name='robotProfile',
        ),
        migrations.DeleteModel(
            name='Routine',
        ),
        migrations.DeleteModel(
            name='Points',
        ),
        migrations.DeleteModel(
            name='RobotProfile',
        ),
    ]
