# Generated by Django 2.2.5 on 2020-12-11 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0009_points_routine'),
    ]

    operations = [
        migrations.CreateModel(
            name='RobotProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('linkedRoutine', models.IntegerField()),
            ],
        ),
    ]
